### ISSUE TITLE
Add ‘Set 20% tax’ button on 'Invoices'

### ISSUE THREAD

**Issue by JSanchez-Davies** [jisc-services/Monitor-Local-Feedback#3]
**Request:** As a user, I want to be able to automatically calculate VAT (20%) for Invoice costings in the same way as I can in the ‘Academic Outputs’ section. 

**Acceptance criteria:**
- Include the ‘Set 20% tax’ button in ‘Invoices’ > ‘Invoice lines/Cost items’ > ‘Add invoice a cost item’

**Comment by Plymgithub** [comment]
The current 20% button on the Academic outputs section doesn't seem to allow me to enter and save a gross value alone.  I have to deduct VAT, enter the NET value, and apply 20% tax to get the full gross amount and save the entry.  Is this the case for others?  If so, can the bug be fixed before the feature is rolled out to the invoices section?

**Comment by JSanchez-Davies** [comment]
Hi there Jason,

Just to make sure we're on the same page, for the 'Save' button to activate, the minimum fields to complete are: Category, Currency and Gross value (gross then should automatically populate the net value with the same figure-- unless you set the tax, of course).  If you set 20% Tax, you should still be able to edit the gross value.  Only the Net can't be edited in this scenario.  However, the reverse happens if you enter the Net value first, i.e. you can't then edit the gross value without amending the tax.  

Is this not the case for you?  Let me know and we could set up a call to take a closer look.

**Comment by Plymgithub** [comment]
Hi Jenny,
Thank you!  I shall make sure I am completing thr mandatory fields next time.
Jason
